Traceback (most recent call last):
  File "main.py", line 50, in <module>
    main()
  File "main.py", line 46, in main
    run(**args_dict)
  File "/users/youyang9/lsg/Megatron-LM/scripts/summa/piz_daint/summa_mlp.py", line 138, in summa_mlp_run
    input_tensor = torch.rand((batch_size, input_row, hidden_dim)).cuda()
RuntimeError: [enforce fail at CPUAllocator.cpp:64] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 419430400000 bytes. Error code 12 (Cannot allocate memory)
Traceback (most recent call last):
  File "main.py", line 50, in <module>
    main()
  File "main.py", line 46, in main
    run(**args_dict)
  File "/users/youyang9/lsg/Megatron-LM/scripts/summa/piz_daint/summa_mlp.py", line 138, in summa_mlp_run
    input_tensor = torch.rand((batch_size, input_row, hidden_dim)).cuda()
RuntimeError: [enforce fail at CPUAllocator.cpp:64] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 419430400000 bytes. Error code 12 (Cannot allocate memory)
Traceback (most recent call last):
  File "main.py", line 50, in <module>
    main()
  File "main.py", line 46, in main
    run(**args_dict)
  File "/users/youyang9/lsg/Megatron-LM/scripts/summa/piz_daint/summa_mlp.py", line 138, in summa_mlp_run
    input_tensor = torch.rand((batch_size, input_row, hidden_dim)).cuda()
RuntimeError: [enforce fail at CPUAllocator.cpp:64] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 419430400000 bytes. Error code 12 (Cannot allocate memory)
Traceback (most recent call last):
  File "main.py", line 50, in <module>
    main()
  File "main.py", line 46, in main
    run(**args_dict)
  File "/users/youyang9/lsg/Megatron-LM/scripts/summa/piz_daint/summa_mlp.py", line 138, in summa_mlp_run
    input_tensor = torch.rand((batch_size, input_row, hidden_dim)).cuda()
RuntimeError: [enforce fail at CPUAllocator.cpp:64] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 419430400000 bytes. Error code 12 (Cannot allocate memory)
srun: error: nid05485: task 1: Exited with exit code 1
srun: Terminating job step 26286402.0
slurmstepd: error: *** STEP 26286402.0 ON nid05484 CANCELLED AT 2020-10-16T06:35:39 ***
srun: error: nid05486: task 2: Exited with exit code 1
srun: error: nid05487: task 3: Exited with exit code 1
srun: error: nid05484: task 0: Terminated
srun: Force Terminated job step 26286402.0
